### PR TITLE
Fixed unaligned accesses in HelloWorldCPU16BPP

### PR DESCRIPTION
**Pull request by Nabile-Rahmani**
As per the VR4300 user manual, the CPU should throw an address error exception when unaligned accesses occur.

image

>If either of the low-order two bits of the address are not zero, an address error exception occurs.

```asm
  FFFFFFFF80001140: AC8C0000 SW $T4[0xFFFFFFFFF801F801], $A0[0xFFFFFFFFA010FC32], 0
[...]
  FFFFFFFF80001140: AC8C0000 SW $T4[0xFFFFFFFFF801F801], $A0[0xFFFFFFFFA010FC36], 0
[...]
  FFFFFFFF80001140: AC8C0000 SW $T4[0xFFFFFFFFF801F801], $A0[0xFFFFFFFFA010FC3A], 0
[...]
  FFFFFFFF80001140: AC8C0000 SW $T4[0xFFFFFFFFF801F801], $A0[0xFFFFFFFFA010FC3E], 0
```

Some existing emulators mask the word writes and ensure they are aligned at the word boundary, though I'm not sure this is the proper behaviour.
Mine currently doesn't care about all that and so it bleeds over the boundary:
image

Doing aligned memory accesses through LH/SH will fix this issue, but that highlights an interesting question regarding the behaviour of the real CPU in those cases.

I would expect the previous version of this ROM to enter an exception on hardware, and I don't think the code has set an handler up to deal with it, so the image would stop rendering as soon as it hits such an access.

image

### CODE REVIEW

**Comment by bryanperris** [comment]
Is this where the code loads the font through 4 byte reads but the address increments by 2?  This did trigger my internal invalid alignment check in debug memory mode, I had to comment it out to prevent crashing but did not have any graphical glitches appear like in your screenshot.  It did kind of baffle me on why it was written like that or if MIPS didn't care due to missing an exception handler.

**Comment by Nabile-Rahmani** [comment]
@bryanperris Yeah, it both loaded the font and stored drawn pixels at unaligned boundaries, it's something the hardware wouldn't allow. I still don't have my 64drive to test, though we could poke people who do on Discord64 to confirm.

**Comment by bryanperris** [comment]
@Nabile-Rahmani Waiting on the backorder too?

**Comment by Nabile-Rahmani** [comment]
A month from now and I'll celebrate the first anniversary :p

**Comment by bryanperris** [comment]
I will be celebrating a year.

**Comment by Nabile-Rahmani** [comment]
We're in this together, yay !

**Comment by bryanperris** [comment]
So maybe 5 more years...

**Comment by Nabile-Rahmani** [comment]
@bryanperris We've confirmed the exception happens on hardware, and doesn't let the store go through. The old ROM only prints a couple pixels from the aligned write before halting.

**Pull request merged**
